excluded: # paths to ignore during linting. Takes precedence over `included`.
  - FinnishPassphrases/Supporting Files/Log.swift
  - MockingbirdSupport/
  - MockingbirdMocks/
identifier_name:
    excluded:
    - id
