name: Xcode - Test

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: install xcbeautify
        run: brew install xcbeautify
      - name: resolve derived date path for mockingbird
        run: echo "DERIVED_DATA="$(xcodebuild -showBuildSettings | sed -n 's|.*BUILD_ROOT = \(.*\)/Build/.*|\1|p')"" >> $GITHUB_ENV
      - name: print derived path
        run: echo "${{ env.DERIVED_DATA }}"
      - name: configure mockingbird
        run: $ "${{ env.DERIVED_DATA }}/SourcePackages/checkouts/mockingbird/mockingbird" configure FinnishPassphrasesTests -- --targets FinnishPassphrases
      - name: Run the xcode tests
        run: xcodebuild -configuration "Debug" ARCHS="x86_64" -destination 'platform=macOS' -project "FinnishPassphrases.xcodeproj" -scheme "FinnishPassphrases" test clean | xcbeautify

